// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKc0gJcZPjUIhqrIAtg5INs8dcnE_hoYk',
    appId: '1:214377979732:web:5aa9044fab547fd87132c1',
    messagingSenderId: '214377979732',
    projectId: 'solvery-tukangin',
    authDomain: 'solvery-tukangin.firebaseapp.com',
    storageBucket: 'solvery-tukangin.appspot.com',
    measurementId: 'G-19HGPWQ3ML',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsDmPWMvBkOKcPuM2ECquACY9Xu8ZK1to',
    appId: '1:214377979732:android:af9a7b50a84f410e7132c1',
    messagingSenderId: '214377979732',
    projectId: 'solvery-tukangin',
    storageBucket: 'solvery-tukangin.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpBx4IhXDYrvvSrI7vmxghp9HEyCHXozw',
    appId: '1:214377979732:ios:30c67991a232b6027132c1',
    messagingSenderId: '214377979732',
    projectId: 'solvery-tukangin',
    storageBucket: 'solvery-tukangin.appspot.com',
    iosClientId: '214377979732-dp24ujen91s6m8mnonu83l463svqbgse.apps.googleusercontent.com',
    iosBundleId: 'com.example.testDrive',
  );
}
